### ISSUE TITLE
Working Perfectly! But where to find the key?

### ISSUE THREAD

**Issue by notflip** [itsmewes/gotp#2]
I have 3 entries in my Google Authenticator on my phone, Where can I find the key (564HJKHJKHKKKHGJKHJKYUFHFGHJ65E) to enter into this repo?

**Comment by wesmartin** [comment]
Hi @notflip 

Glad it is working well for you 😊

I have tried to find out myself but I'm also not able to get the key from Google Authenticator. I had to unlink my 2fa and then set it up again to get the key. Sorry, it's not ideal but I couldn't find another way to do it. If you find a way, please let me know and I'll add it to the README.

**Comment by notflip** [comment]
Do you know what the official term or name for that key is? It's hard to google since a 'key' could in this case also mean the key that gotp returns

**Comment by wesmartin** [comment]
@notflip 

I believe the term is _secret key_ where what is generated by the Google Authenticator and Gotp is called a _verification code_

**Comment by notflip** [comment]
@wesmartin I'm not sure about this but can a Secret key live in two places? Or is it an "or" situations? Where I can have it in here, but not in my Google Authenticator at the same time?

**Comment by wesmartin** [comment]
@notflip you can have it in multiple places. I have my keys stored in Gotp and Google Authenticator as a backup or if I don't have my computer with me.

**Comment by notflip** [comment]
https://github.com/dim13/otpauth.git 
this looks like the thing we need, trying it out today. You can export your keys in the Google Auth app, and then scan the QR code, the package above will transform the QR code to the string we need (I hope)

**Comment by notflip** [comment]
@wesmartin I got it working using the above.

**Comment by wesmartin** [comment]
@notflip thanks for letting me know. I did some testing as well and found that any QR code scanner will show what the secret key is. There will be some other text in what is returned by the QR code by the secret will be there 😊
